---
title: "PV03_PCA"
output: html_document
date: "2024-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**This markdown follows after 02_PopStats.Rmd** 

#Load libraries
```{r}
library(dartR)
library(adegenet)
library(poppr)
library(hierfstat)
library(reshape2)
library(ggplot2)
library(RColorBrewer)
library(scales)
library(dplyr)
```

```{r}
load("Data/pver_gen.RData")
```


#3. PCA

##3.1 PCA model 
```{r}
x = tab(pver_gen, NA.method = "mean")

# Perform PCA
pca1 = dudi.pca(x, scannf = FALSE, scale = FALSE, nf = 3)

# Analyse how much percent of genetic variance is explained by each axis
percent = pca1$eig/sum(pca1$eig)*100
barplot(percent, ylab = "Genetic variance explained by eigenvectors (%)", ylim = c(0,12),
        names.arg = round(percent, 1))
```


##3.2 PCA coord dataframe 
```{r}
# Create a data.frame containing individual coordinates
ind_coords = as.data.frame(pca1$li) 

# Rename columns of dataframe
colnames(ind_coords) = c("Axis1","Axis2","Axis3")

# Add a column containing individuals
ind_coords$Ind = indNames(pver_gen)

# Add a column with the site IDs
ind_coords$Site = pver_gen$pop

# Calculate centroid (average) position for each population
centroid = aggregate(cbind(Axis1, Axis2, Axis3) ~ Site, data = ind_coords, FUN = mean)

# Add centroid coordinates to ind_coords dataframe
ind_coords = left_join(ind_coords, centroid, by = "Site", suffix = c("",".cen"))

# Define colour palette
cols = brewer.pal(nPop(pver_gen), "Set3")

# Custom x and y labels
xlab = paste("Axis 1 (", format(round(percent[1], 1), nsmall=1)," %)", sep="")
ylab = paste("Axis 2 (", format(round(percent[2], 1), nsmall=1)," %)", sep="")
```

##4.4 Theme for PCA
```{r}
theme_PCA <-theme(aspect.ratio = 3/5) +
  theme(axis.line = element_blank()) +
  theme(plot.background = element_blank(),
    panel.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank()) +
 theme(panel.border = element_rect(colour = "black", fill=NA, size=1))
```

```{r}
#define colour palette for each reef. 
reef_names <- c("CapeGrenville", "PCB", "Cairns", "Townsville", "Swains", "CapBunk", "CS1", "CS2", "CS3", "CS4", "CS5", "CS6")
reef_pal <- c("#9E0142", "#D53E4F", "#F46D43", "#FDAE61", "#FEE08B", "#FFFFBF", 
              "#C51B7D", "#5E4FA2", "#3288BD","#66C2A5","#ABDDA4","#E6F598")

names(reef_pal) <- reef_names

theme_PCA <-theme(aspect.ratio = 3/5) +
  theme(axis.line = element_blank()) +
  theme(plot.background = element_blank(),
    panel.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank()) +
 theme(panel.border = element_rect(colour = "black", fill=NA, linewidth=1))
```


##4.5 Plot PCA by sector
```{r}
ind_coords

ind_coords.full <- ind_coords %>% mutate(Site = factor(Site, levels = c("CapeGrenville", "PCB", "Cairns", "Townsville", "Swains", "CapBunk", "CS1", "CS2", "CS3", "CS4", "CS5", "CS6")))


PCA <- ind_coords.full %>% 
  ggplot(aes(Axis1, Axis2, fill = Site)) +
  geom_point(alpha = 1, shape = 21, size = 3) + 
  scale_fill_manual(values = reef_pal) +
  labs(x = xlab, y = ylab) +
  theme_PCA

PCA
```